pipelines:
  - name: demo_application
    steps:
      - name: bld_backend
        type: MvnBuild
        configuration:
          sourceLocation: .
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: be_gitRepo
          integrations:
            - name: artimus
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - "11"
        execution:
          onStart:
            - javac -version
            - mvn --version
 
      
      - name: publish_app_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: build_app
          outputResources:
            - name: appl_build_info
 
      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: libs-release-local
          integrations:
            - name: artimus
          inputResources:
            - name: appl_build_info
          outputResources:
            - name: appl_promoted_build_info
