apiVersion: v1.1
pipelines:
  - name:   <string>
    steps:
      - name: <string>
        type: MvnBuild
        configuration:
          #inherits from bash
          mvnCommand:       <string>      # required
          sourceLocation:   <string>      # required
          configLocation:   <string>      # required
          configFileName:   <string>      # required
 
          integrations:
            - name:         <artifactory integration>  # required
          inputResources:
            - name:         <gitrepo resource>         # required
            - name:         <filespec resource>        # optional
          outputResources:
            - name:         <buildinfo resource>       # if autoPublishBuildInfo is true
 
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete:                                  #always
            - echo "Cleaning up some stuff"
